name: booking-order-app # change this to your app name
services:
  user-service: # change this to your service name
    container_name: field-service # change this to your service name
    image: sikoding20/field-service # change this to your image name
    ports:
      - "8002:8002" # change this to your port
    env_file:
      - .env